### ISSUE TITLE
XH 1.7: NOTICE: Undefined index: show_heading

### ISSUE THREAD

**Issue by cmb69** [cmb69/onepage_xh#33]
`$pageData['show_heading` has been removed as of CMSimple_XH 1.7, so the [unconditional test](https://github.com/cmb69/onepage_xh/blob/1.0beta2/classes/Controller.php#L286) is erroneous. Actually, the whole method `::replaceAlternativeHeading()` doesn't make sense under CMSimple_XH 1.7.

**Comment by lck-git** [comment]
Gibt es dafür schon einen Quick-Fix?

**Comment by cmb69** [comment]
Man könnte wohl [diese Zeile](https://github.com/cmb69/onepage_xh/blob/1.0beta2/classes/Controller.php#L286) durch folgende ersetzen:
````php
        if (isset($pageData['shpw_heading']) && $pageData['show_heading'] == '1') {
````

**Comment by lck-git** [comment]
Sehr schön, danke. Damit verschwindet die Notice.
