### ISSUE TITLE
Use a class for onepage_menu not an id

### ISSUE THREAD

**Issue by lck-git** [cmb69/onepage_xh#34]
Problem: Wenn man das OnePage-Menü 2x in der template.htm aufrufen will (1x für ein Desktop-Menü und 1x für ein mobiles Menü), dan ergeben sich doppelte ID's, die laut Spezifikation nur einmal vorkommen sollten. Der W3 Validator beanstandet dies auch als Fehler "Duplicate ID"
https://github.com/cmb69/onepage_xh/blob/b1823de3f5ca016508b48220b4d7d220c6ed511e/classes/Li.php#L38

https://github.com/cmb69/onepage_xh/blob/b1823de3f5ca016508b48220b4d7d220c6ed511e/onepage.js#L295

**Comment by cmb69** [comment]
Ich denke, die Umstellung auf eine Klasse sollte keine besonderen Probleme bereiten (außer für Templates, die eine ID erwarten). Andererseits: ist es wirklich nötig, das Menü zweimal auszugeben? Es gibt da ja ein paar Möglichkeiten, [CSS entsprechend zu nutzen](https://maurice-web.de/reihenfolge-von-elementen-mit-transform-umkehren/).

**Comment by lck-git** [comment]
Natürlich gibt es Möglichkeiten, aber manchmal ist es halt einfacher/praktikabler ein Menü 2x auszugeben, z.B. ein horizontales CSS-Menü und ein völlig anders aussehendes vertikales mobiles Menü und da werden halt die doppelten ID's als Fehler eingestuft (W3 Validator).
Bei toc() wird das ja auch nicht gemacht und da ist eine Mehrfachausgabe sehr verbreitet, siehe Template mini1, mini2, fhs-simple.

Ich würde grundsätzlich abraten, zumindest bei Plugins, eine ID zu verwenden, ausser es ist zwingend notwendig. Bei lb_gallery ist das z.B. auch ein Problem, da man eine Galerie ja auch mehrfach in einer Seite ausgeben kann, Ergebnis siehe [hier](https://validator.w3.org/nu/?doc=http%3A%2F%2Fholgerirmler.de%2Ffcbtmp%2F%3FZwei_Galerien), "Duplicate ID".

**Comment by cmb69** [comment]
> Ich würde grundsätzlich abraten, zumindest bei Plugins, eine ID zu verwenden, ausser es ist zwingend notwendig.

Ja, da hast du natürlich recht.

**Comment by lck-git** [comment]
Du kannst aber auch so lassen!
In dem Fall ist es nicht weiter tragisch, da die doppelten ID's nicht gleichzeitig aktiv sind. Soll der W3-Validator meckern bis er schwarz wird.
Also Issue löschen.
